#!/usr/bin/env bash
#
# deploy/provision_cdn.sh — one-time (idempotent) creation of the private S3
# bucket and the CloudFront distribution (two origins: S3 via Origin Access
# Control; the Lambda Function URL via a shared-secret custom header, NOT
# OAC — research.md Decision 7 amendment. OAC/SigV4 signing for the Lambda
# origin requires the *viewer* request to already carry a precomputed
# x-amz-content-sha256 body-hash header, which a plain HTML <form> POST
# never sends, so real registration/feedback submissions were rejected with
# InvalidSignatureException. Instead this script tells CloudFront to inject
# a fixed secret header on every request it forwards to the Lambda origin
# (read from deploy/.origin-verify-secret, generated by
# provision_lambda.sh), and lambda_handler.py rejects anything that doesn't
# carry it — the Function URL's own AuthType is NONE).
#
# DOMAIN is OPTIONAL. Without it, the distribution is created on its
# default *.cloudfront.net address using CloudFront's own free default
# certificate — fully usable for testing before a real domain is bought
# (plan.md Constraints: never invent or assume a domain is available).
# Re-run later with DOMAIN=yourdomain.com once you have one: this script
# then requests the ACM certificate and UPDATES the existing distribution
# in place to add the alias — it does not need to be recreated.
#
# Requires: deploy/provision_lambda.sh already run (needs the Function URL).
# AWS CLI v2, credentials with S3/ACM/CloudFront/Lambda permissions.
#
# This is the most complex of the provisioning scripts and the least
# testable without a real AWS account — review it carefully before running.
# NOT executed or verified in the environment that authored it.

set -euo pipefail

# See provision_lambda.sh for why: Git Bash/MSYS auto-"path-converts" any
# `/...`-shaped substring in an argument passed to a native Windows exe —
# demonstrated in practice to corrupt an unrelated string value, not just
# whole-argument paths. This script's CloudFront distribution config JSON
# contains path patterns like "/register*" that are not local paths at all
# and must not be touched.
export MSYS_NO_PATHCONV=1

AWS_REGION="${AWS_REGION:-eu-central-1}"
BUCKET_NAME="${BUCKET_NAME:?BUCKET_NAME is required (globally unique), e.g. BUCKET_NAME=quorum-public-site ./deploy/provision_cdn.sh}"
DOMAIN="${DOMAIN:-}"
FUNCTION_NAME="${FUNCTION_NAME:-quorum-public}"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

SECRET_FILE="$SCRIPT_DIR/.origin-verify-secret"
if [ ! -f "$SECRET_FILE" ]; then
  echo "ERROR: $SECRET_FILE not found — run ./deploy/provision_lambda.sh first (it generates this secret)." >&2
  exit 1
fi
ORIGIN_VERIFY_SECRET="$(cat "$SECRET_FILE")"

if [ -z "$DOMAIN" ]; then
  echo "No DOMAIN set — provisioning without a custom domain for now."
  echo "The distribution will be reachable at its default *.cloudfront.net address."
  echo "Re-run with DOMAIN=yourdomain.com once you've bought one to add it."
  echo
fi

ACCOUNT_ID="$(aws sts get-caller-identity --query Account --output text)"

echo "== 1/6 Private S3 bucket =="
if aws s3api head-bucket --bucket "$BUCKET_NAME" 2>/dev/null; then
  echo "Bucket '$BUCKET_NAME' already exists."
else
  if [ "$AWS_REGION" = "us-east-1" ]; then
    aws s3api create-bucket --bucket "$BUCKET_NAME" --region "$AWS_REGION"
  else
    aws s3api create-bucket --bucket "$BUCKET_NAME" --region "$AWS_REGION" \
      --create-bucket-configuration LocationConstraint="$AWS_REGION"
  fi
  aws s3api put-public-access-block --bucket "$BUCKET_NAME" --public-access-block-configuration \
    BlockPublicAcls=true,IgnorePublicAcls=true,BlockPublicPolicy=true,RestrictPublicBuckets=true
fi

CERT_ARN=""
if [ -n "$DOMAIN" ]; then
  echo "== 2/6 ACM certificate (requested in us-east-1 specifically — a hard CloudFront requirement regardless of AWS_REGION) =="
  EXISTING_CERT_ARN="$(aws acm list-certificates --region us-east-1 \
    --query "CertificateSummaryList[?DomainName=='$DOMAIN'].CertificateArn | [0]" --output text 2>/dev/null || echo "None")"
  if [ "$EXISTING_CERT_ARN" != "None" ] && [ -n "$EXISTING_CERT_ARN" ]; then
    CERT_ARN="$EXISTING_CERT_ARN"
    echo "Certificate already requested: $CERT_ARN"
  else
    CERT_ARN="$(aws acm request-certificate --region us-east-1 \
      --domain-name "$DOMAIN" --validation-method DNS \
      --query CertificateArn --output text)"
    echo "Certificate requested: $CERT_ARN"
  fi

  echo "ACTION MAY BE REQUIRED: if this is a new certificate, add the DNS validation record ACM asks for:"
  echo "  aws acm describe-certificate --region us-east-1 --certificate-arn $CERT_ARN --query 'Certificate.DomainValidationOptions'"
  echo "Waiting for certificate validation (pauses here until that record is in place and has propagated)..."
  aws acm wait certificate-validated --region us-east-1 --certificate-arn "$CERT_ARN"
else
  echo "== 2/6 ACM certificate — skipped (no DOMAIN set) =="
fi

echo "== 3/6 Origin Access Control — S3 =="
S3_OAC_ID="$(aws cloudfront list-origin-access-controls \
  --query "OriginAccessControlList.Items[?Name=='quorum-s3-oac'].Id | [0]" --output text 2>/dev/null || echo "None")"
if [ "$S3_OAC_ID" = "None" ] || [ -z "$S3_OAC_ID" ]; then
  S3_OAC_ID="$(aws cloudfront create-origin-access-control --origin-access-control-config '{
    "Name": "quorum-s3-oac",
    "SigningProtocol": "sigv4",
    "SigningBehavior": "always",
    "OriginAccessControlOriginType": "s3"
  }' --query OriginAccessControl.Id --output text)"
fi

FUNCTION_URL="$(aws lambda get-function-url-config --region "$AWS_REGION" --function-name "$FUNCTION_NAME" \
  --query FunctionUrl --output text)"
FUNCTION_URL_HOST="$(echo "$FUNCTION_URL" | sed -E 's#https://##; s#/$##')"

echo "== 4/6 CloudFront distribution (S3 default origin; /register*, /feedback*, /events*, /metrics* -> Lambda) =="
# CachePolicyId/OriginRequestPolicyId values below are AWS's own managed
# policies (CachingOptimized, CachingDisabled, AllViewer) — stable, documented
# IDs, but verify with `aws cloudfront list-cache-policies` /
# `list-origin-request-policies` if AWS ever changes them.
DIST_ID="$(aws cloudfront list-distributions \
  --query "DistributionList.Items[?Comment=='quorum-public'].Id | [0]" --output text 2>/dev/null || echo "None")"

if [ -n "$DOMAIN" ]; then
  ALIASES_JSON="{\"Quantity\": 1, \"Items\": [\"$DOMAIN\"]}"
  VIEWER_CERT_JSON="{\"ACMCertificateArn\": \"$CERT_ARN\", \"SSLSupportMethod\": \"sni-only\", \"MinimumProtocolVersion\": \"TLSv1.2_2021\"}"
else
  ALIASES_JSON='{"Quantity": 0, "Items": []}'
  VIEWER_CERT_JSON='{"CloudFrontDefaultCertificate": true}'
fi

if [ "$DIST_ID" != "None" ] && [ -n "$DIST_ID" ]; then
  echo "Distribution already exists: $DIST_ID"
  GET_OUTPUT="$(aws cloudfront get-distribution-config --id "$DIST_ID")"
  NEEDS_UPDATE=false

  CURRENT_ROOT="$(echo "$GET_OUTPUT" | python -c "import json,sys; print(json.load(sys.stdin)['DistributionConfig'].get('DefaultRootObject',''))")"
  if [ "$CURRENT_ROOT" != "index.html" ]; then
    echo "DefaultRootObject is not set to index.html (found: '${CURRENT_ROOT:-<empty>}') — requests to / would 404/403. Fixing."
    NEEDS_UPDATE=true
  fi

  if [ -n "$DOMAIN" ]; then
    CURRENT_ALIASES="$(echo "$GET_OUTPUT" | python -c "import json,sys; print(' '.join(json.load(sys.stdin)['DistributionConfig']['Aliases'].get('Items', [])))")"
    if echo "$CURRENT_ALIASES" | tr ' ' '\n' | grep -qx "$DOMAIN"; then
      echo "Domain '$DOMAIN' is already configured on this distribution."
    else
      echo "Adding domain '$DOMAIN' to the existing distribution."
      NEEDS_UPDATE=true
    fi
  fi

  CURRENT_LAMBDA_OAC="$(echo "$GET_OUTPUT" | python -c "
import json, sys
data = json.load(sys.stdin)['DistributionConfig']
for o in data['Origins']['Items']:
    if o['Id'] == 'lambda-origin':
        print(o.get('OriginAccessControlId', ''))
        break
")"
  CURRENT_HEADER_VALUE="$(echo "$GET_OUTPUT" | python -c "
import json, sys
data = json.load(sys.stdin)['DistributionConfig']
for o in data['Origins']['Items']:
    if o['Id'] == 'lambda-origin':
        for h in o.get('CustomHeaders', {}).get('Items', []):
            if h['HeaderName'] == 'x-quorum-origin-verify':
                print(h['HeaderValue'])
        break
")"
  CURRENT_LAMBDA_DOMAIN="$(echo "$GET_OUTPUT" | python -c "
import json, sys
data = json.load(sys.stdin)['DistributionConfig']
for o in data['Origins']['Items']:
    if o['Id'] == 'lambda-origin':
        print(o.get('DomainName', ''))
        break
")"
  if [ -n "$CURRENT_LAMBDA_OAC" ] || [ "$CURRENT_HEADER_VALUE" != "$ORIGIN_VERIFY_SECRET" ]; then
    echo "Lambda origin needs migrating from OAC signing to the shared-secret header (or the secret changed)."
    NEEDS_UPDATE=true
  fi
  if [ "$CURRENT_LAMBDA_DOMAIN" != "$FUNCTION_URL_HOST" ]; then
    echo "Lambda origin's DomainName is stale (found: $CURRENT_LAMBDA_DOMAIN, current Function URL: $FUNCTION_URL_HOST) — the function was likely recreated. Fixing."
    NEEDS_UPDATE=true
  fi

  if [ "$NEEDS_UPDATE" = "true" ]; then
    ETAG="$(echo "$GET_OUTPUT" | python -c "import json,sys; print(json.load(sys.stdin)['ETag'])")"
    NEW_CONFIG="$(echo "$GET_OUTPUT" | python -c "
import json, sys
data = json.load(sys.stdin)['DistributionConfig']
data['DefaultRootObject'] = 'index.html'
if '$DOMAIN':
    data['Aliases'] = json.loads('''$ALIASES_JSON''')
    data['ViewerCertificate'] = json.loads('''$VIEWER_CERT_JSON''')
for o in data['Origins']['Items']:
    if o['Id'] == 'lambda-origin':
        o['OriginAccessControlId'] = ''
        o['DomainName'] = '$FUNCTION_URL_HOST'
        o['CustomHeaders'] = {
            'Quantity': 1,
            'Items': [{'HeaderName': 'x-quorum-origin-verify', 'HeaderValue': '$ORIGIN_VERIFY_SECRET'}]
        }
print(json.dumps(data))
")"
    aws cloudfront update-distribution --id "$DIST_ID" --distribution-config "$NEW_CONFIG" --if-match "$ETAG" >/dev/null
    echo "Distribution updated in place — deploying the change (can take several minutes to propagate)."
  fi
else
  DIST_CONFIG="$(cat <<JSON
{
  "CallerReference": "quorum-public-$(date +%s)",
  "Comment": "quorum-public",
  "Enabled": true,
  "DefaultRootObject": "index.html",
  "Aliases": $ALIASES_JSON,
  "ViewerCertificate": $VIEWER_CERT_JSON,
  "Origins": {
    "Quantity": 2,
    "Items": [
      {
        "Id": "s3-origin",
        "DomainName": "$BUCKET_NAME.s3.$AWS_REGION.amazonaws.com",
        "S3OriginConfig": {"OriginAccessIdentity": ""},
        "OriginAccessControlId": "$S3_OAC_ID"
      },
      {
        "Id": "lambda-origin",
        "DomainName": "$FUNCTION_URL_HOST",
        "CustomHeaders": {
          "Quantity": 1,
          "Items": [{"HeaderName": "x-quorum-origin-verify", "HeaderValue": "$ORIGIN_VERIFY_SECRET"}]
        },
        "CustomOriginConfig": {
          "HTTPPort": 80,
          "HTTPSPort": 443,
          "OriginProtocolPolicy": "https-only",
          "OriginSslProtocols": {"Quantity": 1, "Items": ["TLSv1.2"]}
        }
      }
    ]
  },
  "DefaultCacheBehavior": {
    "TargetOriginId": "s3-origin",
    "ViewerProtocolPolicy": "redirect-to-https",
    "AllowedMethods": {"Quantity": 2, "Items": ["GET", "HEAD"], "CachedMethods": {"Quantity": 2, "Items": ["GET", "HEAD"]}},
    "CachePolicyId": "658327ea-f89d-4fab-a63d-7e88639e58f6",
    "Compress": true
  },
  "CacheBehaviors": {
    "Quantity": 4,
    "Items": [
      {"PathPattern": "/register*", "TargetOriginId": "lambda-origin", "ViewerProtocolPolicy": "redirect-to-https", "AllowedMethods": {"Quantity": 7, "Items": ["GET","HEAD","OPTIONS","PUT","POST","PATCH","DELETE"], "CachedMethods": {"Quantity": 2, "Items": ["GET","HEAD"]}}, "CachePolicyId": "4135ea2d-6df8-44a3-9df3-4b5a84be39ad", "OriginRequestPolicyId": "b689b0a8-53d0-40ab-baf2-68738e2966ac"},
      {"PathPattern": "/feedback*", "TargetOriginId": "lambda-origin", "ViewerProtocolPolicy": "redirect-to-https", "AllowedMethods": {"Quantity": 7, "Items": ["GET","HEAD","OPTIONS","PUT","POST","PATCH","DELETE"], "CachedMethods": {"Quantity": 2, "Items": ["GET","HEAD"]}}, "CachePolicyId": "4135ea2d-6df8-44a3-9df3-4b5a84be39ad", "OriginRequestPolicyId": "b689b0a8-53d0-40ab-baf2-68738e2966ac"},
      {"PathPattern": "/events*", "TargetOriginId": "lambda-origin", "ViewerProtocolPolicy": "redirect-to-https", "AllowedMethods": {"Quantity": 7, "Items": ["GET","HEAD","OPTIONS","PUT","POST","PATCH","DELETE"], "CachedMethods": {"Quantity": 2, "Items": ["GET","HEAD"]}}, "CachePolicyId": "4135ea2d-6df8-44a3-9df3-4b5a84be39ad", "OriginRequestPolicyId": "b689b0a8-53d0-40ab-baf2-68738e2966ac"},
      {"PathPattern": "/metrics*", "TargetOriginId": "lambda-origin", "ViewerProtocolPolicy": "redirect-to-https", "AllowedMethods": {"Quantity": 7, "Items": ["GET","HEAD","OPTIONS","PUT","POST","PATCH","DELETE"], "CachedMethods": {"Quantity": 2, "Items": ["GET","HEAD"]}}, "CachePolicyId": "4135ea2d-6df8-44a3-9df3-4b5a84be39ad", "OriginRequestPolicyId": "b689b0a8-53d0-40ab-baf2-68738e2966ac"}
    ]
  }
}
JSON
)"
  DIST_ID="$(aws cloudfront create-distribution --distribution-config "$DIST_CONFIG" --query Distribution.Id --output text)"
fi

DIST_ARN="arn:aws:cloudfront::$ACCOUNT_ID:distribution/$DIST_ID"
DIST_DOMAIN="$(aws cloudfront get-distribution --id "$DIST_ID" --query Distribution.DomainName --output text)"

echo "== 5/6 S3 bucket policy (allow only this distribution, via OAC, to read) =="
aws s3api put-bucket-policy --bucket "$BUCKET_NAME" --policy "$(cat <<JSON
{
  "Version": "2012-10-17",
  "Statement": [{
    "Sid": "AllowCloudFrontServicePrincipalReadOnly",
    "Effect": "Allow",
    "Principal": {"Service": "cloudfront.amazonaws.com"},
    "Action": "s3:GetObject",
    "Resource": "arn:aws:s3:::$BUCKET_NAME/*",
    "Condition": {"StringEquals": {"AWS:SourceArn": "$DIST_ARN"}}
  }]
}
JSON
)"

echo "== 6/6 Done (the Lambda Function URL's public-invoke permission is granted by provision_lambda.sh) =="

echo
echo "CloudFront distribution: $DIST_ID"
echo "CloudFront domain: $DIST_DOMAIN"
if [ -n "$DOMAIN" ]; then
  echo "Point $DOMAIN's DNS at: $DIST_DOMAIN (ALIAS in Route 53, or a CNAME at your existing DNS provider)"
else
  echo "No custom domain configured yet — reachable at https://$DIST_DOMAIN/ once deployed."
  echo "Re-run with DOMAIN=yourdomain.com later to add a custom domain (updates this distribution in place)."
fi
echo "Next: ./deploy/release_static.sh && ./deploy/release_lambda.sh"
